name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  video_player: ^2.9.5
  syncfusion_flutter_pdfviewer: ^29.1.35
  flutter_pdfview: ^1.0.7
  path_provider: ^2.0.11
  xml: ^6.5.0
  pointer_interceptor: ^0.10.1+2
  shape_of_view_null_safe: ^3.0.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  lottie: ^3.3.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/g1.svg
    - assets/images/g2.svg
    - assets/images/g3.svg
    - assets/images/g4.svg
    - assets/images/g5.svg
    - assets/images/gg.svg
    - assets/images/g6.svg
    - assets/b1.svg
    - assets/b2.svg
    - assets/b3.svg
    - assets/b4.svg
    - assets/b5.svg
    - assets/b6.svg
    - assets/b7.svg
    - assets/b8.svg
    - assets/b9.svg
    - assets/b10.svg
    - assets/b11.svg
    - assets/ar1.svg
    - assets/ar2.svg
    - assets/ar3.svg
    - assets/ar4.svg
    - assets/ar5.svg
    - assets/ar6.svg
    - assets/ar7.svg
    - assets/ar8.svg
    - assets/ar9.svg
    - assets/ar10.svg
    - assets/ar11.svg
    - assets/en1.svg
    - assets/en2.svg
    - assets/en3.svg
    - assets/en4.svg
    - assets/en5.svg
    - assets/en6.svg
    - assets/en7.svg
    - assets/en8.svg
    - assets/en9.svg
    - assets/en10.svg
    - assets/en11.svg
    - assets/s1.png
    - assets/s2.png
    - assets/s3.png
    - assets/s4.png
    - assets/s5.png
    - assets/s6.png
    - assets/s7.png
    - assets/s8.png
    - assets/s9.png
    - assets/s10.png
    - assets/s11.jpg
    - assets/s12.jpg
    - assets/s13.jpg
    - assets/sm.png
    - assets/any.png
    - assets/sound.mp3
    - assets/s1.mp4
    - assets/s2.mp4
    - assets/s3.mp4
    - assets/s4.mp4
    - assets/p.pdf
    - assets/cv_mostafa_said.pdf
    - assets/t2.pdf
    - assets/t3.pdf
    - assets/t4.pdf
    - assets/1x.pdf
    - assets/ui1.mp4
    - assets/ui2.png
    - assets/ui3.png
    - assets/m1.png
    - assets/sh1.png
    - assets/sh2.png
    - assets/sh3.png
    - assets/sh4.png
    - assets/sh5.png
    - assets/h4.png
    - assets/h5.png
    - assets/h6.png
    - assets/h7.png
    - assets/h8.png
    - assets/h9.png
    - assets/h10.png
    - assets/h11.png
    - assets/h12.png
    - assets/h13.png
    - assets/h14.png
    - assets/3d.png
    - assets/ggg1.png
    - assets/ggg2.png
    - assets/whats.json
    - assets/telegram.json
    - assets/cv_ats_Mostafa_said.pdf




    - assets/1/blender.png
    - assets/1/p1.png
    - assets/1/p2.png
    - assets/1/p3.png
    - assets/1/p4.png
    - assets/1/p5.png
    - assets/1/p6.png
    - assets/1/p7.png
    - assets/1/pp.png
    - assets/1/s.png
    - assets/1/T.png
    - assets/1/v1.png
    - assets/1/v2.png
    - assets/1/v3.png
    - assets/1/v4.png
    - assets/1/i1.png
    - assets/T2.mp4
    - assets/e.png
    - assets/m1.pdf
    - assets/x1.png
    - assets/x2.png
    - assets/x3.png


  fonts:
    - family: Almarai
      fonts:
        - asset: assets/Almarai-Regular.ttf
        - asset: assets/Almarai-ExtraBold.ttf

    - family: Harmattan
      fonts:
        - asset: assets/Harmattan-Bold.ttf

    - family: Andalus
      fonts:
        - asset: assets/Andalus.ttf
